export const BRANCHES_REPOSITORY = 'BRANCHES_REPOSITORY';
export const USERS_REPOSITORY = 'USERS_REPOSITORY';
export const DEPARTMENTS_REPOSITORY = 'DEPARTMENTS_REPOSITORY';
export const ROLES_REPOSITORY = 'ROLES_REPOSITORY';
export const RIGHTS_REPOSITORY = 'RIGHTS_REPOSITORY';
export const COMPANIES_REPOSITORY = 'COMPANIES_REPOSITORY';
export const ACC_HEADS_REPOSITORY = 'ACC_HEADS_REPOSITORY';
export const VOUCHERS_REPOSITORY = 'VOUCHERS_REPOSITORY';
export const PNR_BOOKINGS_REPOSITORY = 'PNR_BOOKINGS_REPOSITORY';
export const PNR_USERS_REPOSITORY = 'PNR_USERS_REPOSITORY';
export const PROMOTIONS_REPOSITORY = 'PROMOTIONS_REPOSITORY';
export const COMMISSION_PERCENTAGE_REPOSITORY =
  'COMMISSION_PERCENTAGE_REPOSITORY';
export const PNRPAYMENT_REPOSITORY = 'PNRPAYMENT_REPOSITORY';
export const SEO_AIRLINES_DATA_REPOSITORY = 'SEO_AIRLINES_DATA_REPOSITORY';
export const BLOGS_REPOSITORY = 'BLOGS_REPOSITORY';
